/// @file    ScriptCallbackKind.hpp
/// @brief   DLL 間の診断入口へ渡すスクリプトコールバック種別。
/// @author  Hasegawa Jin
/// @date    2026-10-03
#pragma once

#include <cstdint>

namespace fbzz::scene {

enum class ScriptCallbackKind : uint8_t {
    UNKNOWN, AWAKE, START, ENABLE, DISABLE, UPDATE, FIXED_UPDATE, LATE_UPDATE, DESTROY,
    DRAW_GIZMOS, DRAW_GIZMOS_SELECTED, PRE_RENDER, POST_RENDER, SETUP_RENDER_PASSES,
    COLLISION_ENTER, COLLISION_STAY, COLLISION_EXIT, TRIGGER_ENTER, TRIGGER_STAY, TRIGGER_EXIT,
    NAV_DESTINATION_REACHED, NAV_PATH_FAILED, NAV_TARGET_SPOTTED, NAV_TARGET_LOST,
    ANIMATION_EVENT, ANIMATOR_MOVE, SEQUENCE_EVENT, SEQUENCE_FINISHED,
    VALIDATE, BEFORE_SERIALIZE, AFTER_DESERIALIZE, SPAWN, DESPAWN,
    DEFERRED, FRAME_DELAY, EVENT_HANDLER, COROUTINE_STEP
};

} /// @note namespace fbzz::scene
