[camera]
sensitivity = 0.30000001192092896
speed = 5.0

[scene]
last_path = 'C:\Users\jinhs\Downloads\FBZZ_Engine\assets\scenes\test.fbzz'

[snap]
distance = 1.0
enabled = false

[view]
show_grid = true