[build]
development = true
output_dir = 'Builds/MyGame'
product_name = 'MyGame'
version = '1.0.0'

[[scenes]]
enabled = true
path = 'Assets/Scenes/Main.scene'

[[scenes]]
enabled = true
path = 'Assets/Scenes/Load.scene'

[[scenes]]
enabled = true
path = 'Assets/Scenes/Result.scene'

[[scenes]]
enabled = true
path = 'Assets/Scenes/Title.scene'