// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: BulletShooterComponent.hpp
#pragma once

#undef  FBZZ_GENERATED_BODY
#define FBZZ_GENERATED_BODY() \
    void Reflect(IReflector& r_) override { \
        r_.Group("Prefab"); \
        r_.Field("Bullet Prefab", bulletPrefab); \
        r_.Field("Muzzle", muzzle); \
        r_.Field("Camera Override", cameraRef); \
        r_.Group("Firing"); \
        r_.Field("Fire Key", fireKey); \
        r_.FloatRange("Fire Rate", fireRate, 0.1f, 30.0f); \
    }
