// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: BulletComponent.hpp
#pragma once

namespace sandbox {
inline void BulletComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Field("Speed", speed);
    r_.Field("Lifetime", lifetime);
    r_.Field("Effect Lifetime", effectLifetime);
    r_.Field("Effect Prefab", effectPrefab);
    r_.Field("Ignore Tag", ignoreTag);
}
} // namespace sandbox
