// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: PlayerWorldSpaceUIComponent.hpp
#pragma once

namespace sandbox {
inline void PlayerWorldSpaceUIComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Field("Target Name", targetName);
    r_.Field("Display Name", displayName);
    r_.Field("Head Offset", headOffset);
}
} // namespace sandbox
