// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: PlayerWorldSpaceUIComponent.hpp
#pragma once

#undef  FBZZ_GENERATED_BODY
#define FBZZ_GENERATED_BODY() \
    void Reflect(IReflector& r_) override { \
        r_.Field("Target Name", targetName); \
        r_.Field("Display Name", displayName); \
        r_.Field("Head Offset", headOffset); \
    }
