// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: SceneManagerScript.hpp
#pragma once

namespace sandbox {
inline void SceneManagerScript::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Field("Target Scene", targetScene);
    r_.Field("Via Scene", viaScene);
    r_.Field("Auto Transition", autoTransition);
    r_.Field("Auto Delay", autoDelay);
}
} // namespace sandbox
