// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: TpsCameraComponent.hpp
#pragma once

#undef  FBZZ_GENERATED_BODY
#define FBZZ_GENERATED_BODY() \
    void Reflect(IReflector& r_) override { \
        r_.Field("Target Tag", targetTag); \
        r_.FloatRange("Distance", distance, 0.5f, 30.0f); \
        r_.FloatRange("Height", height, -5.0f, 10.0f); \
        r_.Field("Yaw", yaw); \
        r_.Field("Pitch", pitch); \
        r_.FloatRange("Min Pitch", minPitch, -90.0f, 0.0f); \
        r_.FloatRange("Max Pitch", maxPitch, 0.0f, 90.0f); \
        r_.FloatRange("Mouse Sensitivity", mouseSensitivity, 0.01f, 5.0f); \
        r_.Field("Mouse Orbit", mouseOrbit); \
        r_.FloatRange("Follow Speed", followSpeed, 0.0f, 50.0f); \
    }
