// GreenWare
// ScriptList.inl — スクリプト登録 X-macro リスト
// ScriptCodeGen が自動更新する。手動編集しないこと。
//   EXE 側 (GameMain.cpp):
//     #define FBZZ_SCRIPT_ENTRY(ns, T) FBZZ_REGISTER_SCRIPT(::ns::T)
//     #include "Scripts/ScriptList.inl"
//     #undef FBZZ_SCRIPT_ENTRY
//   DLL 側 (GreenWareScriptsDll.cpp):
//     #define FBZZ_SCRIPT_ENTRY(ns, T) \
//         { ::ns::T::TYPE_NAME, []() { ret std::make_unique<::ns::T>(); } },
//     #include "Scripts/ScriptList.inl"
//     #undef FBZZ_SCRIPT_ENTRY
// ScriptCodeGen は Assets/**/*.hpp の FBZZ_SCRIPT(...) をスキャンして、この範囲を自動同期する。

// @@FBZZ_SCRIPT_ENTRIES_BEGIN — ScriptCodeGen が自動挿入するため編集しないこと
FBZZ_SCRIPT_ENTRY(sandbox, BossCameraDirectorComponent)
FBZZ_SCRIPT_ENTRY(sandbox, FpsCameraComponent)
FBZZ_SCRIPT_ENTRY(sandbox, TpsCameraComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossAiComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossAnimatorComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossAudioComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossBeamComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossBreakComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossCollapsePostureComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossCoreComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossDeathVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossHatchComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossHealthBarComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossHitboxRigComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossLegDebrisComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossLegHealthBarComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossPartComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossPartTelegraphComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossRigComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossRoomTriggerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossShockwaveComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossStepDustComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BossTelegraphComponent)
FBZZ_SCRIPT_ENTRY(sandbox, DangerWallComponent)
FBZZ_SCRIPT_ENTRY(sandbox, EnemyDeathVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, EnemyHealthComponent)
FBZZ_SCRIPT_ENTRY(sandbox, EyeSpriteComponent)
FBZZ_SCRIPT_ENTRY(sandbox, LaserVolleyComponent)
FBZZ_SCRIPT_ENTRY(sandbox, LoomAiComponent)
FBZZ_SCRIPT_ENTRY(sandbox, LoomBossComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentAiComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentApertureComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentBodyComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentBossComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentDeathVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentHitboxRigComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentPathComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentRigComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentSpineComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ArenaBoundsComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ArenaHazardComponent)
FBZZ_SCRIPT_ENTRY(sandbox, CameraFollowManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, CameraShakeManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ChainDisplayComponent)
FBZZ_SCRIPT_ENTRY(sandbox, CombatManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, GameFlowComponent)
FBZZ_SCRIPT_ENTRY(sandbox, GameSettingsComponent)
FBZZ_SCRIPT_ENTRY(sandbox, HitstopManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ImpactFeedbackManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ResultFieldGridComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ResultPresenterComponent)
FBZZ_SCRIPT_ENTRY(sandbox, RumbleManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ScreenEffectManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, TimeManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, VfxManagerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, AimMarkerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BladeComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerAimComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerBossBlockComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerClimbComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerControllerComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerHeadLookComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerHealthBarComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerHealthComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PlayerParryComponent)
FBZZ_SCRIPT_ENTRY(sandbox, WeaponRigComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SceneManagerScript)
FBZZ_SCRIPT_ENTRY(sandbox, ControlsGuideComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ElectricMinusParticleComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ElectricPlusParticleComponent)
FBZZ_SCRIPT_ENTRY(sandbox, OptionsScreenComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ScreenDressingComponent)
FBZZ_SCRIPT_ENTRY(sandbox, TitleFieldGridComponent)
FBZZ_SCRIPT_ENTRY(sandbox, TitleMenuComponent)
FBZZ_SCRIPT_ENTRY(sandbox, StageSelectComponent)
FBZZ_SCRIPT_ENTRY(sandbox, UiHeroTextComponent)
FBZZ_SCRIPT_ENTRY(sandbox, UiHintBarComponent)
FBZZ_SCRIPT_ENTRY(sandbox, UiRevealComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BeamTrailRendererComponent)
FBZZ_SCRIPT_ENTRY(sandbox, GameCursorComponent)
FBZZ_SCRIPT_ENTRY(sandbox, GlowPartComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SeWarmupComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BeamScorchVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BladeChargeGlowComponent)
FBZZ_SCRIPT_ENTRY(sandbox, BladeTrailComponent)
FBZZ_SCRIPT_ENTRY(sandbox, DodgeAfterimageComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ExecuteVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ImpactVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ParryVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, PartDamageHudComponent)
FBZZ_SCRIPT_ENTRY(sandbox, RunDustVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentBiteVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentGeyserVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentRushVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentSlamVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SerpentSnapVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SlashHitVfxComponent)
FBZZ_SCRIPT_ENTRY(sandbox, SlashScarComponent)
FBZZ_SCRIPT_ENTRY(sandbox, ToppleVfxComponent)
// @@FBZZ_SCRIPT_ENTRIES_END
