// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: EnemyControllerComponent.hpp
#pragma once

namespace sandbox {
inline void EnemyControllerComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("Target");
    r_.Field("Target Tag", targetTag);
    r_.Group("Movement");
    r_.FloatRange("Move Speed", moveSpeed, 0.1f, 12.0f);
    r_.FloatRange("Stop Distance", stopDistance, 0.1f, 5.0f);
    r_.FloatRange("Rotation Speed", rotationSpeed, 0.1f, 30.0f);
    r_.FloatRange("Model Yaw Offset", modelYawOffsetDegrees, 0.0f, 360.0f);
    r_.Group("Attack");
    r_.FloatRange("Attack Range", attackRange, 0.1f, 5.0f);
    r_.FloatRange("Attack Cooldown", attackCooldown, 0.1f, 10.0f);
    r_.FloatRange("Attack Windup Delay", attackWindupDelay, 0.0f, 3.0f);
    r_.FloatRange("Knockback Speed", knockbackSpeed, 0.0f, 12.0f);
    r_.Group("Defense");
    r_.FloatRange("Block Range", blockRange, 0.1f, 5.0f);
    r_.FloatRange("Block Duration", blockDuration, 0.1f, 3.0f);
    r_.FloatRange("Block Cooldown", blockCooldown, 0.1f, 5.0f);
    r_.Group("Animator Params");
    r_.Field("Speed Param", paramSpeed);
    r_.Field("Attack Trigger Param", paramAttackTrigger);
    r_.Field("Block Param", paramBlock);
}
} // namespace sandbox
