// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: HitBloodEffectComponent.hpp
#pragma once

namespace sandbox {
inline void HitBloodEffectComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("Particle");
    r_.Field("Local Offset", localOffset);
    r_.Field("Emit Velocity", emitVelocity);
    r_.Field("Gravity", gravity);
    r_.Field("Color Start", colorStart);
    r_.Field("Color End", colorEnd);
    r_.FloatRange("Size Start", sizeStart, 0.01f, 1.0f);
    r_.FloatRange("Size End", sizeEnd, 0.0f, 1.0f);
    r_.FloatRange("Lifetime", lifetime, 0.05f, 3.0f);
    r_.FloatRange("Velocity Spread", velocitySpread, 0.0f, 8.0f);
    r_.Field("Burst Count", burstCount);
}
} // namespace sandbox
