// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: PlayerControllerComponent.hpp
#pragma once

namespace sandbox {
inline void PlayerControllerComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("Movement");
    r_.FloatRange("Move Speed", moveSpeed, 0.1f, 20.0f);
    r_.FloatRange("Sprint Multiplier", sprintMultiplier, 1.0f, 5.0f);
    r_.FloatRange("Strafe Speed Mult", strafeSpeedMultiplier, 0.1f, 1.0f);
    r_.FloatRange("Jump Force", jumpForce, 0.1f, 30.0f);
    r_.FloatRange("Model Yaw Offset", modelYawOffsetDegrees, 0.0f, 360.0f);
    r_.FloatRange("Ground Accel", groundAccel, 1.0f, 100.0f);
    r_.FloatRange("Ground Decel", groundDecel, 1.0f, 100.0f);
    r_.FloatRange("Air Accel", airAccel, 0.0f, 50.0f);
    r_.FloatRange("Turn Speed", turnSpeed, 0.1f, 30.0f);
    r_.Field("Use Camera Forward", useCameraForward);
    r_.Field("Rotate To Move Dir", rotateToMoveDirection);
    r_.Field("Use Foot IK", useFootIK);
    r_.Group("Key Bindings");
    r_.Field("Forward", keyForward);
    r_.Field("Backward", keyBackward);
    r_.Field("Left", keyLeft);
    r_.Field("Right", keyRight);
    r_.Field("Jump", keyJump);
    r_.Field("Sprint", keySprint);
    r_.Group("Animator Params");
    r_.Field("Speed Param", paramSpeed);
    r_.Field("Vertical Speed Param", paramVerticalSpeed);
    r_.Field("IsGrounded Param", paramIsGrounded);
    r_.Field("Jump Trigger Param", paramJumpTrigger);
}
} // namespace sandbox
