// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: SwordParticleComponent.hpp
#pragma once

namespace sandbox {
inline void SwordParticleComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("References");
    r_.Field("Player Tag", playerTag);
    r_.Group("Particle");
    r_.Field("Color Start", colorStart);
    r_.Field("Color End", colorEnd);
    r_.FloatRange("Size Start", sizeStart, 0.01f, 1.0f);
    r_.FloatRange("Size End", sizeEnd, 0.00f, 1.0f);
    r_.FloatRange("Emit Rate", emitRate, 1.0f, 500.0f);
    r_.Field("Texture Path", texturePath);
}
} // namespace sandbox
