// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: SwordTrailComponent.hpp
#pragma once

namespace sandbox {
inline void SwordTrailComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("References");
    r_.Field("Owner Name", ownerName);
    r_.Group("Timing");
    r_.FloatRange("Swing Start Time", swingStartTime, 0.0f, 1.0f);
    r_.FloatRange("Swing End Time", swingEndTime, 0.0f, 1.0f);
    r_.Group("Trail");
    r_.FloatRange("Duration", duration, 0.02f, 2.0f);
    r_.FloatRange("Sample Interval", sampleInterval, 0.001f, 0.1f);
    r_.FloatRange("Min Vertex Dist", minVertexDist, 0.0f, 1.0f);
    r_.FloatRange("Width Start", widthStart, 0.01f, 1.0f);
    r_.FloatRange("Width End", widthEnd, 0.0f, 1.0f);
    r_.Field("Color Start", colorStart);
    r_.Field("Color End", colorEnd);
    r_.Field("Max Points", maxPoints);
    r_.Field("Smooth Subdivisions", smoothSubdivisions);
    r_.Field("Material Path", materialPath);
    r_.Field("Texture Path", texturePath);
    r_.Group("Blood Particle");
    r_.Field("Blood Emit Velocity", bloodEmitVelocity);
    r_.Field("Blood Gravity", bloodGravity);
    r_.Field("Blood Color Start", bloodColorStart);
    r_.Field("Blood Color End", bloodColorEnd);
    r_.FloatRange("Blood Size Start", bloodSizeStart, 0.01f, 1.0f);
    r_.FloatRange("Blood Size End", bloodSizeEnd, 0.0f, 1.0f);
    r_.FloatRange("Blood Lifetime", bloodLifetime, 0.05f, 3.0f);
    r_.FloatRange("Blood Velocity Spread", bloodVelocitySpread, 0.0f, 8.0f);
    r_.Field("Blood Burst Count", bloodBurstCount);
}
} // namespace sandbox
