// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually
// Source: WeaponHitboxComponent.hpp
#pragma once

namespace sandbox {
inline void WeaponHitboxComponent::Reflect(::fbzz::scene::IReflector& r_) {
    r_.Group("Hitbox");
    r_.Field("Hitbox Type", hitboxType);
    r_.Field("Owner Name", ownerName);
    r_.Field("Collider Center", colliderCenter);
    r_.Field("Collider Size", colliderSize);
    r_.FloatRange("Swing Start Time", swingStartTime, 0.0f, 1.0f);
    r_.FloatRange("Swing End Time", swingEndTime, 0.0f, 1.0f);
    r_.Group("Impact");
    r_.Field("Impact Trigger Param", impactTriggerParam);
    r_.Field("Hit Trigger Param", hitTriggerParam);
    r_.FloatRange("Impact Cooldown", impactCooldown, 0.0f, 2.0f);
}
} // namespace sandbox
