// @file    Localization_ja.inl
// @brief   エディター UI の日本語訳。原文 (英語) が鍵。
// @author  Hasegawa Jin
// @date    2026-09-08
//
// Localization.cpp からのみ include される Pair の初期化子リスト。
//
// 訳を足すとき:
//   1. 原文は**呼び出し側の文字列と 1 文字も違わないこと**。空白・"..." ・大文字小文字まで
//      一致しないと引けない (鍵は原文そのものなので、綴りが違えば別の項目になる)。
//   2. 訳が無い文字列は英語のまま出る。壊れはしないので、埋まっていない箇所は
//      Project Settings > Editor の «未訳» 一覧で確認して順に足していく。
//   3. ウィジェットのラベルは Localization.cpp が "###原文" を付ける。ここには
//      訳だけを書くこと。

// ── パネル ─────────────────────────────────────────────────────────────────
{ "AI Settings",               "AI 設定" },
{ "Analysis",                  "解析" },
{ "Animation Graph",           "アニメーショングラフ" },
{ "Animation Mask Preview",    "アニメーションマスク プレビュー" },
{ "Asset Browser",             "Asset Browser" },
{ "Asset Maintenance",         "アセット保守" },
{ "Behavior Tree",             "ビヘイビアツリー" },
{ "Build Output",              "ビルド出力" },
{ "Build Settings",            "ビルド設定" },
{ "Console",                   "Console" },
{ "Dependency View",           "依存関係" },
{ "Hotkey Editor",             "ホットキー設定" },
{ "IBL Baker",                 "IBL ベイク" },
{ "Inspector",                 "インスペクター" },
{ "Map Tools",                 "マップツール" },
{ "Navigation",                "ナビゲーション" },
{ "Preview",                   "プレビュー" },
{ "Project Settings",          "プロジェクト設定" },
{ "SFX Editor",                "SFX エディター" },
{ "Scene Hierarchy",           "ヒエラルキー" },
{ "Search",                    "検索" },
{ "Sequence",                  "シーケンス" },
{ "Sprite Editor",             "スプライトエディター" },
{ "Undo History",              "操作履歴" },
{ "VFX Timeline",              "VFX タイムライン" },
{ "Scene View",                "シーンビュー" },
{ "Game View",                 "ゲームビュー" },

// ── メニューの見出し ────────────────────────────────────────────────────────
{ "File",                      "ファイル" },
{ "Edit",                      "編集" },
{ "View",                      "表示" },
{ "Debug",                     "デバッグ" },
{ "Tools",                     "ツール" },
{ "AI",                        "AI" },
{ "Panels",                    "パネル" },
{ "Scene Camera",              "シーンカメラ" },
{ "Terrain & Map",             "地形とマップ" },
{ "NavMesh Draw Mode",         "NavMesh の表示" },
{ "View Mode",                 "描画モード" },
{ "Assets",                    "アセット" },
{ "Editors",                   "エディター" },
{ "Settings",                  "設定" },
{ "Animation",                 "アニメーション" },
{ "Viewport",                  "ビューポート" },
{ "Selection",                 "選択" },
{ "Gizmo",                     "ギズモ" },
{ "Render",                    "描画" },
{ "Effects",                   "エフェクト" },
{ "Terrain",                   "地形" },
{ "AssetBrowser",              "" },

// ── ファイル操作 ────────────────────────────────────────────────────────────
{ "New Scene",                 "新規シーン" },
{ "Open Scene...",             "シーンを開く..." },
{ "Save",                      "保存" },
{ "Save Prefab",               "プレハブを保存" },
{ "Save Scene As...",          "名前を付けてシーンを保存..." },
{ "Save All Assets",           "すべてのアセットを保存" },
{ "Save Asset",                "アセットを保存" },
{ "Close Prefab",              "プレハブ編集を終える" },
{ "Edit Prefab",               "プレハブを編集" },
{ "Open Asset",                "アセットを開く" },
{ "Open Asset Import Settings", "インポート設定を開く" },
{ "Exit",                      "終了" },

// ── 編集操作 ────────────────────────────────────────────────────────────────
{ "Undo",                      "元に戻す" },
{ "Redo",                      "やり直す" },
{ "Copy",                      "コピー" },
{ "Paste",                     "貼り付け" },
{ "Paste As Child",            "子として貼り付け" },
{ "Duplicate",                 "複製" },
{ "Delete Selected",           "選択を削除" },
{ "Rename",                    "名前を変更" },
{ "Rename Node",               "ノード名を変更" },
{ "Select All",                "すべて選択" },
{ "Clear Selection",           "選択を解除" },
{ "Selection Back",            "選択を戻る" },
{ "Selection Forward",         "選択を進む" },
{ "Copy Transform",            "Transform をコピー" },
{ "Paste Transform",           "Transform を貼り付け" },
{ "Reset Transform",           "Transform をリセット" },
{ "Reset Component",           "コンポーネントをリセット" },
{ "Move Component Up",         "コンポーネントを上へ" },
{ "Move Component Down",       "コンポーネントを下へ" },

// ── 表示・カメラ ────────────────────────────────────────────────────────────
{ "Frame Selected",            "選択を画面に収める" },
{ "Toggle Orthographic",       "平行投影を切り替え" },
{ "View Front",                "正面" },
{ "View Back",                 "背面" },
{ "View Left",                 "左" },
{ "View Right",                "右" },
{ "View Top",                  "上" },
{ "View Bottom",               "下" },
{ "UI Scale",                  "UI スケール" },
{ "Set UI Scale",              "UI スケールを設定" },
{ "Reset UI Scale",            "UI スケールを戻す" },
{ "Show / Hide Panel",         "パネルの表示を切り替え" },
{ "Focus Panel",               "パネルを前面へ" },
{ "List Panels",               "パネル一覧" },
{ "Command Palette",           "コマンドパレット" },
{ "Shortcut List",             "ショートカット一覧" },

// ── 再生 ────────────────────────────────────────────────────────────────────
{ "Play",                      "再生" },
{ "Play / Stop",               "再生 / 停止" },
{ "Pause",                     "一時停止" },
{ "Step",                      "1 フレーム進める" },
{ "Stop",                      "停止" },
{ "Reload Scripts",            "スクリプトを再読み込み" },
{ "Hot Reload",                "ホットリロード" },

// ── ギズモとスナップ ────────────────────────────────────────────────────────
{ "Gizmo: Move",               "ギズモ: 移動" },
{ "Gizmo: Rotate",             "ギズモ: 回転" },
{ "Gizmo: Scale",              "ギズモ: 拡縮" },
{ "Gizmo: World / Local",      "ギズモ: ワールド / ローカル" },
{ "Gizmo: Pivot / Center",     "ギズモ: ピボット / 中心" },
{ "Toggle Grid Snap",          "グリッドスナップを切り替え" },

// ── デバッグ表示 ────────────────────────────────────────────────────────────
{ "Grid",                      "グリッド" },
{ "Show Grid",                 "グリッドを表示" },
{ "Light Range",               "ライトの範囲" },
{ "Show Light Range",          "ライトの範囲を表示" },
{ "VFX Force Fields / Emitters", "VFX の力場 / エミッター" },
{ "Show VFX Gizmos",           "VFX ギズモを表示" },
{ "Skeleton",                  "スケルトン" },
{ "Show Skeleton",             "スケルトンを表示" },
{ "Show Ragdoll",              "ラグドールを表示" },
{ "Stats",                     "統計" },
{ "Show Stats",                "統計を表示" },
{ "Colliders",                 "コライダー" },
{ "Show Colliders",            "コライダーを表示" },
{ "Terrain Collision",         "地形の当たり判定" },
{ "Show Terrain Collision",    "地形の当たり判定を表示" },
{ "NavMesh",                   "NavMesh" },
{ "Show NavMesh",              "NavMesh を表示" },
{ "Set NavMesh Draw Mode",     "NavMesh の表示を設定" },
{ "AI Sensors",                "AI センサー" },
{ "Show AI Sensors",           "AI センサーを表示" },
{ "Decal Bounds",              "デカールの範囲" },
{ "Show Decal Bounds",         "デカールの範囲を表示" },
{ "Scene View Occlusion Culling", "シーンビューのオクルージョンカリング" },
{ "Particle Overdraw View",    "パーティクルの重なり表示" },
{ "Shadow",                    "影" },
{ "Shadows",                   "影" },
{ "Solid",                     "ソリッド" },
{ "Transparent",               "半透明" },
{ "Areas",                     "エリア" },
{ "Portals",                   "ポータル" },
{ "Voxels",                    "ボクセル" },
{ "Lit",                       "ライトあり" },
{ "Unlit",                     "ライトなし" },
{ "Wireframe Lit",             "ワイヤーフレーム (ライトあり)" },
{ "Wireframe Unlit",           "ワイヤーフレーム (ライトなし)" },
{ "Set View Mode",             "描画モードを設定" },

// ── ツール ──────────────────────────────────────────────────────────────────
{ "Map Editing Mode",          "マップ編集モード" },
{ "Terrain Tool",              "地形ツール" },
{ "Water Tool",                "水面ツール" },
{ "Resize Terrain",            "地形をリサイズ" },
{ "Build Settings...",         "ビルド設定..." },
{ "Project Settings...",       "プロジェクト設定..." },
{ "IBL Baker...",              "IBL ベイク..." },
{ "Navigation...",             "ナビゲーション..." },
{ "Asset Maintenance...",      "アセット保守..." },
{ "AI Settings...",            "AI 設定..." },
{ "Bake All NavMesh",          "NavMesh を全てベイク" },
{ "AI Command Bus",            "AI コマンドバス" },
{ "Editor Command Bus",        "エディターコマンドバス" },
{ "Refresh Asset Browser",     "アセットブラウザーを更新" },
{ "Reveal Asset in Browser",   "ブラウザーで表示" },
{ "Auto Layout States",        "ステートを自動配置" },
{ "Set State Position",        "ステートの位置を設定" },
{ "Auto Layout Behavior Tree", "ビヘイビアツリーを自動配置" },
{ "Control Effect",            "エフェクトを操作" },
{ "Preview SFX",               "SFX を試聴" },
{ "Save SFX",                  "SFX を保存" },
{ "Load SFX Preset",           "SFX プリセットを読み込み" },
{ "Randomize SFX",             "SFX をランダム生成" },
{ "Mutate SFX",                "SFX を少し変える" },
{ "Inspect SFX",               "SFX を調べる" },
{ "Set SFX Parameter",         "SFX パラメーターを設定" },
{ "Set SFX Wave",              "SFX の波形を設定" },
{ "Export SFX to .wav",        "SFX を .wav へ書き出し" },

// ── Project Settings パネル ────────────────────────────────────────────────
{ "Application",               "アプリケーション" },
{ "Graphics",                  "グラフィックス" },
{ "Physics",                   "物理" },
{ "Layer Collision Matrix",    "レイヤー衝突行列" },
{ "Unchecked pairs never collide. Triggers are filtered too.",
  "チェックを外した組は衝突しない。トリガーも同じく除外される" },
{ "Name at least two layers in Tags & Layers to edit the matrix.",
  "行列を編集するには「タグとレイヤー」でレイヤーに 2 つ以上名前を付ける" },
{ "Input",                     "入力" },
{ "Audio",                     "オーディオ" },
{ "Tags & Layers",             "タグとレイヤー" },
{ "Import",                    "インポート" },
{ "Editor",                    "エディター" },
{ "Search...",                 "検索..." },
{ "Language",                  "言語" },
{ "Scenes",                    "シーン" },
{ "Screen",                    "画面" },
{ "Cursor",                    "カーソル" },
{ "Rendering",                 "描画" },
{ "Debug Visualization",       "デバッグ表示" },
{ "Selection Outline",         "選択の輪郭" },
{ "Tags",                      "タグ" },
{ "Layers",                    "レイヤー" },
{ "Actions",                   "アクション" },
{ "Axes",                      "軸" },
{ "Connected Gamepads",        "接続中のゲームパッド" },
{ "FBX Defaults",              "FBX の既定値" },
{ "Import Presets",            "インポートプリセット" },
{ "Exclude Patterns",          "除外パターン" },
{ "User Settings (preview)",   "ユーザー設定 (プレビュー)" },

{ "Applies immediately. Saved to editor_settings.toml.",
  "選ぶとすぐ切り替わります。editor_settings.toml に保存されます。" },
{ "Translation Coverage",      "訳の埋まり具合" },
{ "Entries",                   "登録数" },
{ "Untranslated (seen this session)", "未訳 (この起動中に出たもの)" },
{ "Open the panels you want translated, then add these to Localization_ja.inl.",
  "訳したいパネルを開いてから、ここに出た原文を Localization_ja.inl へ足してください。" },
{ "Copy to Clipboard",         "クリップボードへコピー" },

// ── コンポーネントのカード名: 訳さない ──────────────────────────────────────
// Transform / Rigid Body / Mesh Renderer は «読む文章» ではなく «打つ・検索する
// 識別子» で、GetComponent<RigidBodyComponent>() ・.scene の中身・エラーメッセージ・
// 資料と同じ綴りである価値が、訳す価値より大きい。「メッシュレンダラー」は
// "Mesh Renderer" より長いだけで、分かりやすさは増えない。
//
// 同じ理由でエンジン / グラフィックスの専門語 (Bloom, Exposure, Roughness, Metallic,
// LOD, IBL, NavMesh, TAA, Substep, Compliance …) も英語のまま置く。訳すのは
// それらを «説明する文章» の方 ── 用語を訳すと文献やコードと照合できなくなる。
//
// 訳を "" にすると «英語のままにすると決めた» 印になり、未訳リストに出なくなる。
// 決めたことを書き残しておかないと、次に見た人が同じ判断をやり直すことになる。
{ "Transform",                 "" },
{ "Camera",                    "" },
{ "Light",                     "" },
{ "Environment Light",         "" },
{ "Mesh Renderer",             "" },
{ "Skinned Mesh Renderer",     "" },
{ "Material",                  "" },
{ "Animator",                  "" },
{ "Bone",                      "" },
{ "IK Solver",                 "" },
{ "LOD Group",                 "" },
{ "Rigid Body",                "" },
{ "Character Controller",      "" },
{ "AABB Collider",             "" },
{ "Box Collider",              "" },
{ "Sphere Collider",           "" },
{ "Capsule Collider",          "" },
{ "Cylinder Collider",         "" },
{ "Terrain Collider",          "" },
{ "Particle Emitter",          "" },
{ "Particle Force Field",      "" },
{ "Trail",                     "" },
{ "Mesh Trail",                "" },
{ "Decal",                     "" },
{ "Post Process Volume",       "" },
{ "Reflection Probe",          "" },
{ "Atmospheric Scattering",    "" },
{ "Volumetric Cloud",          "" },
{ "Sky Renderer",              "" },
{ "Sun Moon Renderer",         "" },
{ "Wind Zone",                 "" },
{ "Water",                     "" },
{ "Volume",                    "" },
{ "Terrain Grid",              "" },
{ "NavMesh Agent",             "" },
{ "NavMesh Modifier",          "" },
{ "NavMesh Patrol",            "" },
{ "NavMesh Sensor",            "" },
{ "NavMesh Surface",           "" },
{ "Off-Mesh Link",             "" },

{ "Remove Component",          "コンポーネントを削除" },
{ "Move Up",                   "上へ" },
{ "Move Down",                 "下へ" },

// ── ユーザープロジェクトの語彙は、ここには置かない ─────────────────────────
// GreenWare のフィールド名・グループ名 (溜め / のけぞり / 弾き / 予告 …) は
// «そのゲームの語彙» であって、エンジンが訳語を持つ筋合いのものではない。
// ここに溜めると、別のプロジェクトを開いてもそのゲームの訳が効いてしまうし、
// エンジンのリポジトリが特定タイトルの用語集を抱えることになる。
//
// プロジェクト側は表示名を最初から自国語で書けばよい:
//     FBZZ_FIELD_RANGE(float, hitRadius, 1.2f, "当たり半径", 0.0f, 5.0f)
//     FBZZ_GROUP("溜め")
// ImGuiReflector::HumanizeName は非 ASCII の表示名を素通しする (整形も辞書引きも
// しない) ので、そのまま Inspector へ出る。2026-09-08 に GreenWare の 938 箇所を
// この形へ移し、ここにあった 260 行を消した。
// ── 共通の語 ────────────────────────────────────────────────────────────────
{ "Add",                       "追加" },
{ "Remove",                    "削除" },
{ "Reset",                     "リセット" },
{ "Apply",                     "適用" },
{ "Cancel",                    "キャンセル" },
{ "OK",                        "OK" },
{ "Close",                     "閉じる" },
{ "Name",                      "名前" },
{ "Type",                      "種類" },
{ "Path",                      "パス" },
{ "Size",                      "サイズ" },
{ "Enabled",                   "有効" },
{ "None",                      "なし" },
{ "Default",                   "既定" },
{ "Refresh",                   "更新" },
{ "Browse...",                 "参照..." },
