// FBZZ Engine
// ScriptCodeGen.cpp | fbzz::editor
// エディター内からのソースコード生成ユーティリティ
#include <Editor/Util/ScriptCodeGen.hpp>
#include <Engine/Core/Logger.hpp>
#include <Engine/Util/FileSystem.hpp>
#include <filesystem>
#include <sstream>
#include <string>
#include <string_view>

namespace fbzz::editor {

namespace {

// ファイルを全行読み込む
std::vector<std::string> ReadLines(const std::string& path)
{
    std::string text;
    if (!util::FileSystem::ReadText(path, text)) return {};
    std::vector<std::string> lines;
    std::string line;
    std::istringstream input(text);
    while (std::getline(input, line))
        lines.push_back(line);
    return lines;
}

// 行リストをファイルに書き出す
bool WriteLines(const std::string& path, const std::vector<std::string>& lines)
{
    std::ostringstream output;
    for (const auto& l : lines) {
        output << l << '\n';
    }
    return util::FileSystem::WriteText(path, output.str());
}

// 既存ファイル内のマーカー行の次に新しい行を挿入する
// marker: 検索するマーカー文字列 (BEGIN マーカー)
bool InsertAfterMarker(const std::string& path,
                       const std::string& marker,
                       const std::string& newLine)
{
    auto lines = ReadLines(path);
    if (lines.empty()) return false;

    for (size_t i = 0; i < lines.size(); ++i) {
        const size_t first = lines[i].find_first_not_of(" \t");
        const std::string_view line = (first == std::string::npos)
            ? std::string_view{}
            : std::string_view(lines[i]).substr(first);
        const std::string expectedMarkerLine = "// " + marker;
        if (line.starts_with(std::string_view(expectedMarkerLine))) {
            size_t insertIndex = i + 1;
            if (marker == "@@FBZZ_SCRIPT_ENTRIES_BEGIN" &&
                insertIndex < lines.size() &&
                lines[insertIndex].find("static const std::vector<ScriptEntry> entries = {") != std::string::npos) {
                ++insertIndex;
            }
            lines.insert(lines.begin() + static_cast<std::ptrdiff_t>(insertIndex), newLine);
            return WriteLines(path, lines);
        }
    }
    FBZZ_LOG_WARN("ScriptCodeGen: marker '%s' not found in %s",
                  marker.c_str(), path.c_str());
    return false;
}

bool EnsureDirectoriesRecursive(const std::string& path)
{
    if (path.empty()) return false;

    return util::FileSystem::EnsureDirectory(util::FileSystem::PathFromUtf8(path));
}

// ScriptCodeGen が生成した既存 TU に Scene.hpp を補い、古いプロジェクトもリンク可能にする。
// WHY: ScriptSceneProxy のテンプレート定義は Scene.hpp 末尾にあるため、Script.hpp だけでは
//      各スクリプト TU に実体化されず、Script DLL のリンク時に未解決シンボルになる。
void EnsureGeneratedScriptTranslationUnit(const std::filesystem::path& headerPath)
{
    std::filesystem::path implementationPath = headerPath;
    implementationPath.replace_extension(".cpp");

    std::string source;
    const std::string implementationPathUtf8 = implementationPath.string();
    if (!util::FileSystem::ReadText(implementationPathUtf8, source)) return;
    if (source.find("AUTO-GENERATED by ScriptCodeGen") == std::string::npos) return;
    if (source.find("#include <Engine/Scene/Scene.hpp>") != std::string::npos) return;

    const size_t scriptInclude = source.find("#include \"Scripts/");
    if (scriptInclude == std::string::npos) return;

    source.insert(scriptInclude,
        "// WHY: ScriptSceneProxy のテンプレート定義をこの TU から参照可能にする。\n"
        "#include <Engine/Scene/Scene.hpp>\n");
    if (!util::FileSystem::WriteText(implementationPathUtf8, source)) {
        FBZZ_LOG_WARN("ScriptCodeGen: failed to update generated TU: %s",
                      implementationPathUtf8.c_str());
    }
}

// C++ スクリプトのテンプレートを生成する
std::string BuildScriptTemplate(const std::string& name)
{
    const std::string className  = name + "Component";
    const std::string genInclude = className + ".generated.hpp";

    std::ostringstream ss;
    ss << "// FBZZ Engine\n";
    ss << "// " << className << ".hpp | sandbox\n";
    ss << "#pragma once\n";
    ss << "\n";
    ss << "#include <Engine/Scene/Script.hpp>\n";
    ss << "\n";
    ss << "using namespace fbzz::scene;\n";
    ss << "using namespace fbzz::math;\n";
    ss << "using namespace fbzz::input;\n";
    ss << "\n";
    ss << "namespace sandbox {\n";
    ss << "\n";
    ss << "class " << className << " : public Script {\n";
    ss << "    FBZZ_SCRIPT(" << className << ")\n";
    ss << "public:\n";
    ss << "    // FBZZ_FIELD(float, speed, 5.0f, \"Speed\")\n";
    ss << "\n";
    ss << "    void OnUpdate(float dt) override;\n";
    ss << "};\n";
    ss << "\n";
    ss << "} // namespace sandbox\n";
    ss << "\n";
    ss << "#include \"" << genInclude << "\"\n";
    ss << "\n";
    ss << "#ifndef " << className << "_IMPL\n";
    ss << "#define " << className << "_IMPL\n";
    ss << "namespace sandbox {\n";
    ss << "\n";
    ss << "inline void " << className << "::OnUpdate(float dt)\n";
    ss << "{\n";
    ss << "    (void)dt;\n";
    ss << "}\n";
    ss << "\n";
    ss << "} // namespace sandbox\n";
    ss << "#endif\n";
    return ss.str();
}

// Surface VS+PS シェーダーテンプレートを生成する
std::string BuildSurfaceHlslTemplate(const std::string& name)
{
    std::ostringstream ss;
    ss << "// FBZZ Engine\n";
    ss << "// Material/Custom/" << name << ".hlsl | Material\n";
    ss << "// " << name << " カスタムマテリアルシェーダー\n";
    ss << "#ifndef " << name << "_HLSL\n";
    ss << "#define " << name << "_HLSL\n";
    ss << "\n";
    ss << "#include \"Common/Constants.hlsli\"\n";
    ss << "#include \"Common/Structs.hlsli\"\n";
    ss << "#include \"Platform/DX11.hlsli\"\n";
    ss << "#include \"Rendering/Lighting.hlsli\"\n";
    ss << "\n";
    ss << "cbuffer MaterialConstants : register(CB_MATERIAL)\n";
    ss << "{\n";
    ss << "    float4 albedo;      // RGBA ベースカラー\n";
    ss << "    uint   textureMask; // テクスチャフラグ\n";
    ss << "};\n";
    ss << "\n";
    ss << "Texture2D    texAlbedo   : register(TEX_ALBEDO);\n";
    ss << "SamplerState sampDefault : register(SAMPLER_DEFAULT);\n";
    ss << "\n";
    ss << "PSInput VSMain(VSInput v)\n";
    ss << "{\n";
    ss << "    PSInput o;\n";
    ss << "    float4 worldPos4 = mul(float4(v.position, 1.0f), world);\n";
    ss << "    o.worldPos   = worldPos4.xyz;\n";
    ss << "    o.svPosition = mul(worldPos4, viewProjection);\n";
    ss << "    o.normal     = normalize(mul(v.normal,  (float3x3)worldInvTranspose));\n";
    ss << "    o.tangent    = normalize(mul(v.tangent, (float3x3)world));\n";
    ss << "    o.uv         = v.uv;\n";
    ss << "    return o;\n";
    ss << "}\n";
    ss << "\n";
    ss << "float4 PSMain(PSInput p) : SV_Target0\n";
    ss << "{\n";
    ss << "    float3 color = (textureMask & 1u)\n";
    ss << "        ? texAlbedo.Sample(sampDefault, p.uv).rgb\n";
    ss << "        : albedo.rgb;\n";
    ss << "    // TODO: ライティング計算をここに追加する\n";
    ss << "    return float4(color, 1.0f);\n";
    ss << "}\n";
    ss << "\n";
    ss << "#endif // " << name << "_HLSL\n";
    return ss.str();
}

// PostProcess フルスクリーン VS+PS テンプレートを生成する
std::string BuildPostProcessHlslTemplate(const std::string& name)
{
    std::ostringstream ss;
    ss << "// FBZZ Engine\n";
    ss << "// PostProcess/Custom/" << name << ".hlsl | PostProcess\n";
    ss << "// " << name << " カスタムポストプロセスシェーダー\n";
    ss << "#ifndef " << name << "_HLSL\n";
    ss << "#define " << name << "_HLSL\n";
    ss << "\n";
    ss << "#include \"Common/Constants.hlsli\"\n";
    ss << "#include \"Common/Structs.hlsli\"\n";
    ss << "#include \"Platform/DX11.hlsli\"\n";
    ss << "\n";
    ss << "Texture2D    texScene    : register(t0);\n";
    ss << "SamplerState sampDefault : register(SAMPLER_DEFAULT);\n";
    ss << "\n";
    ss << "// フルスクリーン三角形用 VS (ジオメトリ不要)\n";
    ss << "PSFullscreenInput VSMain(uint id : SV_VertexID)\n";
    ss << "{\n";
    ss << "    PSFullscreenInput o;\n";
    ss << "    o.uv         = float2((id << 1) & 2, id & 2);\n";
    ss << "    o.svPosition = float4(o.uv * float2(2, -2) + float2(-1, 1), 0, 1);\n";
    ss << "    return o;\n";
    ss << "}\n";
    ss << "\n";
    ss << "float4 PSMain(PSFullscreenInput p) : SV_Target0\n";
    ss << "{\n";
    ss << "    float4 color = texScene.Sample(sampDefault, p.uv);\n";
    ss << "    // TODO: エフェクトをここに追加する\n";
    ss << "    return color;\n";
    ss << "}\n";
    ss << "\n";
    ss << "#endif // " << name << "_HLSL\n";
    return ss.str();
}

// Compute Shader テンプレートを生成する
std::string BuildComputeHlslTemplate(const std::string& name)
{
    std::ostringstream ss;
    ss << "// FBZZ Engine\n";
    ss << "// PostProcess/Custom/" << name << ".cs.hlsl | Compute\n";
    ss << "// " << name << " カスタムコンピュートシェーダー\n";
    ss << "#ifndef " << name << "_CS_HLSL\n";
    ss << "#define " << name << "_CS_HLSL\n";
    ss << "\n";
    ss << "#include \"Common/Constants.hlsli\"\n";
    ss << "#include \"Platform/DX11.hlsli\"\n";
    ss << "\n";
    ss << "RWTexture2D<float4> outputTex : register(u0);\n";
    ss << "Texture2D           inputTex  : register(t0);\n";
    ss << "SamplerState        sampPoint : register(SAMPLER_DEFAULT);\n";
    ss << "\n";
    ss << "[numthreads(8, 8, 1)]\n";
    ss << "void CSMain(uint3 id : SV_DispatchThreadID)\n";
    ss << "{\n";
    ss << "    uint2 dim;\n";
    ss << "    outputTex.GetDimensions(dim.x, dim.y);\n";
    ss << "    if (id.x >= dim.x || id.y >= dim.y) return;\n";
    ss << "\n";
    ss << "    float2 uv    = (float2(id.xy) + 0.5f) / float2(dim);\n";
    ss << "    float4 color = inputTex.SampleLevel(sampPoint, uv, 0);\n";
    ss << "    // TODO: 処理をここに追加する\n";
    ss << "    outputTex[id.xy] = color;\n";
    ss << "}\n";
    ss << "\n";
    ss << "#endif // " << name << "_CS_HLSL\n";
    return ss.str();
}

} // namespace

// =============================================================================
// 公開 API
// =============================================================================

std::string ScriptCodeGen::CreateScript(const std::string& name,
                                        const std::string& scriptsDir,
                                        const std::string& dllCppPath,
                                        const std::string& staticCppPath)
{
    if (name.empty() || scriptsDir.empty()) return {};

    const std::string className  = name + "Component";
    const std::string headerName = className + ".hpp";
    const std::string headerPath = scriptsDir + "/" + headerName;

    // 重複チェック
    if (util::FileSystem::Exists(headerPath)) {
        FBZZ_LOG_WARN("ScriptCodeGen: %s already exists", headerPath.c_str());
        return {};
    }

    // .hpp テンプレートを書き出す
    if (!EnsureDirectoriesRecursive(scriptsDir)) {
        FBZZ_LOG_ERROR("ScriptCodeGen: failed to create Scripts directory: %s", scriptsDir.c_str());
        return {};
    }
    if (!util::FileSystem::WriteText(headerPath, BuildScriptTemplate(name))) {
        FBZZ_LOG_ERROR("ScriptCodeGen: failed to write file: %s", headerPath.c_str());
        return {};
    }

    // .generated.hpp を空実装で事前生成する (FHT が FBZZ_FIELD を検出後に上書きする)
    const std::string genPath = scriptsDir + "/" + className + ".generated.hpp";
    if (!util::FileSystem::Exists(genPath)) {
        std::ostringstream genContent;
        genContent << "// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually\n";
        genContent << "// Source: " << headerName << "\n";
        genContent << "#pragma once\n";
        genContent << "\n";
        genContent << "namespace sandbox {\n";
        genContent << "inline void " << className << "::Reflect(::fbzz::scene::IReflector&) {}\n";
        genContent << "} // namespace sandbox\n";
        util::FileSystem::WriteText(genPath, genContent.str());
    }

    const std::string relInclude = "\"Scripts/" + headerName + "\"";

    // スクリプト専用 TU を生成して DLL ビルドを並列化する。
    // WHY: SandboxScriptsDll.cpp は宣言のみ取り込み (_IMPL 事前定義)、
    //      各 .cpp が実装を担当することで Ninja が TU を並列コンパイルできる。
    const std::string implCppPath = scriptsDir + "/" + className + ".cpp";
    if (!util::FileSystem::Exists(implCppPath)) {
        std::ostringstream implSs;
        implSs << "// AUTO-GENERATED by ScriptCodeGen -- do not edit manually\n";
        implSs << "// WHY: 実装を独立した TU に分離して DLL のビルドを並列化する。\n";
        implSs << "// WHY: ScriptSceneProxy のテンプレート定義を各スクリプト TU から参照可能にする。\n";
        implSs << "#include <Engine/Scene/Scene.hpp>\n";
        implSs << "#include \"Scripts/" << headerName << "\"\n";
        util::FileSystem::WriteText(implCppPath, implSs.str());
    }

    // スクリプトエントリの登録先を決定する。
    // 新形式: scriptsDir/ScriptList.inl が存在すれば一元管理ファイルへ挿入 (EXE/DLL 共通)。
    // 旧形式: ScriptList.inl がない古いプロジェクトは従来通り DLL/EXE の各 .cpp へ挿入。
    const std::string scriptListPath = scriptsDir + "/ScriptList.inl";
    const bool hasScriptList = util::FileSystem::Exists(
        util::FileSystem::PathFromUtf8(scriptListPath));

    // WHY: ScriptList.inl の登録と DLL/EXE 側 include は独立して壊れ得る。
    //      ScriptList に名前があるだけで include 追記をスキップすると、
    //      ファクトリ展開時に型が見えず Script DLL のビルドが失敗する。
    bool scriptListHasEntry = hasScriptList && AlreadyRegistered(scriptListPath, className);

    // DLL 側 include 挿入 (形式: #define Xxx_IMPL + #include "Scripts/Xxx.hpp")
    if (!dllCppPath.empty()) {
        const bool dllAlreadyRegistered = AlreadyRegistered(dllCppPath, className);
        if (!dllAlreadyRegistered)
            InsertScriptIncludeDll(dllCppPath, className, relInclude);

        if (hasScriptList) {
            if (!scriptListHasEntry) {
                InsertScriptListEntry(scriptListPath, className);
                scriptListHasEntry = true;
            }
        } else if (!dllAlreadyRegistered) {
            InsertScriptEntry(dllCppPath, className);  // 旧形式フォールバック
        }
    }

    // EXE 側 include 挿入 (形式: #include "Scripts/Xxx.hpp")
    // WHY: SandboxStandalone は DLL をロードせず EXE 内の静的登録でスクリプトを解決する。
    //      _IMPL なしでフルインクルードするため DLL 側と形式が異なり、include のみ個別管理する。
    //      重複チェックは staticCppPath 自体で行う (ScriptList.inl は DLL ブロックで更新済みのため)。
    if (!staticCppPath.empty()) {
        const bool staticAlreadyRegistered = AlreadyRegistered(staticCppPath, className);
        if (!staticAlreadyRegistered)
            InsertScriptInclude(staticCppPath, relInclude);

        if (hasScriptList) {
            if (!scriptListHasEntry) {
                InsertScriptListEntry(scriptListPath, className);
                scriptListHasEntry = true;
            }
        } else if (!staticAlreadyRegistered) {
            InsertScriptStaticEntry(staticCppPath, className);  // 旧形式フォールバック
        }
    }

    FBZZ_LOG_INFO("ScriptCodeGen: script generated -> %s", headerPath.c_str());
    return headerPath;
}

std::string ScriptCodeGen::CreateHlsl(const std::string& name,
                                      const std::string& hlslDir,
                                      HlslKind kind)
{
    if (name.empty() || hlslDir.empty()) return {};

    std::string subDir;
    std::string fileName;
    std::string content;

    switch (kind) {
    case HlslKind::SurfaceVSPS:
        subDir   = hlslDir + "/Material/Custom";
        fileName = name + ".hlsl";
        content  = BuildSurfaceHlslTemplate(name);
        break;
    case HlslKind::PostProcessVSPS:
        subDir   = hlslDir + "/PostProcess/Custom";
        fileName = name + ".hlsl";
        content  = BuildPostProcessHlslTemplate(name);
        break;
    case HlslKind::ComputeCS:
        subDir   = hlslDir + "/PostProcess/Custom";
        fileName = name + ".cs.hlsl";
        content  = BuildComputeHlslTemplate(name);
        break;
    }

    if (!EnsureDirectoriesRecursive(subDir)) {
        FBZZ_LOG_ERROR("ScriptCodeGen: failed to create HLSL directory: %s", subDir.c_str());
        return {};
    }
    const std::string outPath = subDir + "/" + fileName;

    if (util::FileSystem::Exists(outPath)) {
        FBZZ_LOG_WARN("ScriptCodeGen: %s already exists", outPath.c_str());
        return {};
    }

    if (!util::FileSystem::WriteText(outPath, content)) {
        FBZZ_LOG_ERROR("ScriptCodeGen: failed to write file: %s", outPath.c_str());
        return {};
    }

    FBZZ_LOG_INFO("ScriptCodeGen: HLSL generated -> %s", outPath.c_str());
    return outPath;
}

// =============================================================================
// 内部実装
// =============================================================================

bool ScriptCodeGen::InsertScriptInclude(const std::string& cppPath,
                                        const std::string& headerRelPath)
{
    return InsertAfterMarker(cppPath,
                             "@@FBZZ_SCRIPT_INCLUDES_BEGIN",
                             "#include " + headerRelPath);
}

// DLL 専用: _IMPL を事前定義してから宣言のみ取り込む 2 行を挿入する。
// WHY: 実装は各スクリプトの独立 .cpp が担当するため、DLL エントリポイントでは
//      型定義・ファクトリに必要な宣言だけを取り込めばよい。
bool ScriptCodeGen::InsertScriptIncludeDll(const std::string& dllCppPath,
                                           const std::string& className,
                                           const std::string& headerRelPath)
{
    // "#define FooComponent_IMPL\n#include ..." の 2 行を 1 挿入として扱う
    const std::string lines =
        "#define " + className + "_IMPL\n#include " + headerRelPath;
    return InsertAfterMarker(dllCppPath, "@@FBZZ_SCRIPT_INCLUDES_BEGIN", lines);
}

bool ScriptCodeGen::InsertScriptListEntry(const std::string& scriptListPath,
                                          const std::string& className)
{
    // FBZZ_SCRIPT_ENTRY(ns, T) マクロで展開される形式で挿入する。
    // EXE/DLL どちらのコンシューマーも同じ .inl を異なるマクロ定義で読む。
    const std::string entry = "FBZZ_SCRIPT_ENTRY(sandbox, " + className + ")";
    return InsertAfterMarker(scriptListPath, "@@FBZZ_SCRIPT_ENTRIES_BEGIN", entry);
}

bool ScriptCodeGen::InsertScriptEntry(const std::string& dllCppPath,
                                      const std::string& className)
{
    const std::string entry =
        "        { ::sandbox::" + className + "::TYPE_NAME,"
        " []() { return std::make_unique<::sandbox::" + className + ">(); } },";
    return InsertAfterMarker(dllCppPath, "@@FBZZ_SCRIPT_ENTRIES_BEGIN", entry);
}

bool ScriptCodeGen::InsertScriptStaticEntry(const std::string& staticCppPath,
                                             const std::string& className)
{
    return InsertAfterMarker(staticCppPath,
                             "@@FBZZ_SCRIPT_ENTRIES_BEGIN",
                             "FBZZ_REGISTER_SCRIPT(::sandbox::" + className + ")");
}

bool ScriptCodeGen::AlreadyRegistered(const std::string& dllCppPath,
                                      const std::string& className)
{
    std::string text;
    if (!util::FileSystem::ReadText(dllCppPath, text)) return false;
    std::string line;
    std::istringstream input(text);
    while (std::getline(input, line)) {
        if (line.find(className) != std::string::npos)
            return true;
    }
    return false;
}

// =============================================================================
// FBZZ Header Tool (FHT) — GenerateReflect / GenerateReflectAll
// =============================================================================

namespace {

std::string TrimStr(const std::string& s)
{
    const size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return {};
    const size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

std::string StripQuotes(const std::string& s)
{
    const std::string t = TrimStr(s);
    if (t.size() >= 2 && t.front() == '"' && t.back() == '"')
        return t.substr(1, t.size() - 2);
    return t;
}

// カンマ区切り分割。文字列リテラル・括弧・波括弧をネスト考慮して分割する。
std::vector<std::string> SplitArgs(const std::string& inner)
{
    std::vector<std::string> args;
    std::string cur;
    int parenDepth = 0, braceDepth = 0;
    bool inStr = false;
    for (char c : inner) {
        if (c == '"' && parenDepth == 0 && braceDepth == 0) inStr = !inStr;
        if (!inStr) {
            if (c == '(') ++parenDepth;
            else if (c == ')') --parenDepth;
            else if (c == '{') ++braceDepth;
            else if (c == '}') --braceDepth;
            else if (c == ',' && parenDepth == 0 && braceDepth == 0) {
                args.push_back(cur);
                cur.clear();
                continue;
            }
        }
        cur += c;
    }
    if (!cur.empty()) args.push_back(cur);
    return args;
}

// "MACRO_NAME(...)" の内側を返す。マクロが行内になければ空を返す。
std::string ExtractMacroInner(const std::string& line, const std::string& macroName)
{
    const size_t pos = line.find(macroName);
    if (pos == std::string::npos) return {};
    // 直後に '(' が続く (空白なし) か確認
    const size_t lp = line.find('(', pos + macroName.size());
    if (lp == std::string::npos) return {};
    int depth = 1;
    size_t i = lp + 1;
    while (i < line.size() && depth > 0) {
        if (line[i] == '(') ++depth;
        else if (line[i] == ')') --depth;
        ++i;
    }
    return line.substr(lp + 1, (i - 1) - lp - 1);
}

struct FieldEntry {
    enum class Kind { Group, Field, FieldRange, FieldEnum, FieldReadonly } kind;
    std::string displayName;
    std::string fieldName;
    std::string typeName;    // FIELD_RANGE の型判別用
    std::string minVal;
    std::string maxVal;
    std::vector<std::string> enumLabels;
};

} // anonymous namespace

std::string ScriptCodeGen::GenerateReflect(const std::string& headerPath)
{
    EnsureGeneratedScriptTranslationUnit(std::filesystem::path(headerPath));

    const auto lines = ReadLines(headerPath);
    if (lines.empty()) return {};

    // Step 1: class ClassName : public Script を探してクラス名を取得する
    std::string className;
    for (const auto& raw : lines) {
        const std::string line = TrimStr(raw);
        const size_t classPos = line.find("class ");
        if (classPos == std::string::npos) continue;
        if (line.find(": public Script") == std::string::npos) continue;
        const size_t nameStart = classPos + 6;
        const size_t nameEnd   = line.find_first_of(" \t:{", nameStart);
        if (nameEnd == std::string::npos || nameEnd <= nameStart) continue;
        className = line.substr(nameStart, nameEnd - nameStart);
        break;
    }
    if (className.empty()) {
        FBZZ_LOG_WARN("FHT: class X : public Script not found in %s", headerPath.c_str());
        return {};
    }

    // Step 1b: ユーザー名前空間を検索する (fbzz::* は除外)
    std::string namespaceName = "sandbox"; // default fallback
    for (const auto& raw : lines) {
        const std::string line = TrimStr(raw);
        if (!line.starts_with("namespace ")) continue;
        const size_t nsStart = 10;
        const size_t nsEnd = line.find_first_of(" \t{", nsStart);
        if (nsEnd == std::string::npos) continue;
        const std::string ns = line.substr(nsStart, nsEnd - nsStart);
        if (ns.empty() || ns.find("fbzz") != std::string::npos) continue;
        namespaceName = ns;
        break;
    }

    // Step 2: FBZZ_GROUP / FBZZ_FIELD* マクロをパースしてエントリ列を構築する
    std::vector<FieldEntry> entries;
    for (const auto& raw : lines) {
        const std::string line = TrimStr(raw);

        if (line.find("FBZZ_FIELD_RANGE") != std::string::npos) {
            const std::string inner = ExtractMacroInner(line, "FBZZ_FIELD_RANGE");
            const auto args = SplitArgs(inner);
            if (args.size() >= 6) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::FieldRange;
                e.typeName    = TrimStr(args[0]);
                e.fieldName   = TrimStr(args[1]);
                e.displayName = StripQuotes(args[3]);
                e.minVal      = TrimStr(args[4]);
                e.maxVal      = TrimStr(args[5]);
                entries.push_back(std::move(e));
            }
        } else if (line.find("FBZZ_FIELD_ENUM") != std::string::npos) {
            const std::string inner = ExtractMacroInner(line, "FBZZ_FIELD_ENUM");
            const auto args = SplitArgs(inner);
            if (args.size() >= 5) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::FieldEnum;
                e.typeName    = TrimStr(args[0]);
                e.fieldName   = TrimStr(args[1]);
                e.displayName = StripQuotes(args[3]);
                for (size_t i = 4; i < args.size(); ++i)
                    e.enumLabels.push_back(StripQuotes(args[i]));
                entries.push_back(std::move(e));
            }
        } else if (line.find("FBZZ_COMPUTED") != std::string::npos ||
                   line.find("FBZZ_FIELD_READONLY") != std::string::npos) {
            const bool isComputed = line.find("FBZZ_COMPUTED") != std::string::npos;
            const std::string macroName = isComputed ? "FBZZ_COMPUTED" : "FBZZ_FIELD_READONLY";
            const std::string inner = ExtractMacroInner(line, macroName);
            const auto args = SplitArgs(inner);
            if (args.size() >= 3) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::FieldReadonly;
                e.typeName    = TrimStr(args[0]);
                e.fieldName   = TrimStr(args[1]);
                e.displayName = StripQuotes(args[2]);
                entries.push_back(std::move(e));
            }
        } else if (line.find("FBZZ_FIELD_REF") != std::string::npos) {
            const std::string inner = ExtractMacroInner(line, "FBZZ_FIELD_REF");
            const auto args = SplitArgs(inner);
            if (args.size() >= 3) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::Field;
                e.typeName    = TrimStr(args[0]);
                e.fieldName   = TrimStr(args[1]);
                e.displayName = StripQuotes(args[2]);
                entries.push_back(std::move(e));
            }
        } else if (line.find("FBZZ_FIELD") != std::string::npos &&
                   line.find("FBZZ_FIELD_") == std::string::npos) {
            const std::string inner = ExtractMacroInner(line, "FBZZ_FIELD");
            const auto args = SplitArgs(inner);
            if (args.size() >= 4) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::Field;
                e.typeName    = TrimStr(args[0]);
                e.fieldName   = TrimStr(args[1]);
                e.displayName = StripQuotes(args[3]);
                entries.push_back(std::move(e));
            }
        } else if (line.find("FBZZ_GROUP") != std::string::npos) {
            const std::string inner = ExtractMacroInner(line, "FBZZ_GROUP");
            const auto args = SplitArgs(inner);
            if (args.size() >= 1) {
                FieldEntry e;
                e.kind        = FieldEntry::Kind::Group;
                e.displayName = StripQuotes(args[0]);
                entries.push_back(std::move(e));
            }
        }
    }

    // Step 3: .generated.hpp を書き出す
    const std::filesystem::path hdrFs(headerPath);
    const std::string genPath =
        (hdrFs.parent_path() / (className + ".generated.hpp")).string();

    // Reflect 本体の行を組み立てる
    std::vector<std::string> bodyLines;
    for (const auto& e : entries) {
        std::ostringstream line;
        switch (e.kind) {
        case FieldEntry::Kind::Group:
            line << "r_.Group(\"" << e.displayName << "\");";
            break;
        case FieldEntry::Kind::Field:
            line << "r_.Field(\"" << e.displayName << "\", " << e.fieldName << ");";
            break;
        case FieldEntry::Kind::FieldRange:
            if (e.typeName == "int") {
                // int には FloatRange ではなく Field にフォールバック
                line << "r_.Field(\"" << e.displayName << "\", " << e.fieldName << ");";
            } else {
                line << "r_.FloatRange(\"" << e.displayName << "\", "
                     << e.fieldName << ", " << e.minVal << ", " << e.maxVal << ");";
            }
            break;
        case FieldEntry::Kind::FieldEnum:
            {
                // static ローカル配列を使い std::span を渡す
                const std::string arrName = "kEnumLabels_" + e.fieldName;
                std::ostringstream labels;
                for (size_t i = 0; i < e.enumLabels.size(); ++i) {
                    if (i > 0) labels << ", ";
                    labels << "\"" << e.enumLabels[i] << "\"";
                }
                line << "{ static constexpr const char* " << arrName << "[] = {"
                     << labels.str() << "}; "
                     << "r_.Enum(\"" << e.displayName << "\", (int&)" << e.fieldName
                     << ", {" << arrName << ", " << e.enumLabels.size() << "}); }";
            }
            break;
        case FieldEntry::Kind::FieldReadonly:
            line << "r_.Readonly(\"" << e.displayName << "\", " << e.fieldName << ");";
            break;
        }
        bodyLines.push_back(line.str());
    }

    std::ostringstream ss;
    ss << "// AUTO-GENERATED by FBZZ Header Tool -- do not edit manually\n";
    ss << "// Source: " << hdrFs.filename().string() << "\n";
    ss << "#pragma once\n";
    ss << "\n";
    ss << "namespace " << namespaceName << " {\n";
    ss << "inline void " << className << "::Reflect(::fbzz::scene::IReflector& r_) {\n";
    for (const auto& bl : bodyLines)
        ss << "    " << bl << "\n";
    ss << "}\n";
    ss << "} // namespace " << namespaceName << "\n";

    if (!util::FileSystem::WriteText(genPath, ss.str())) {
        FBZZ_LOG_ERROR("FHT: failed to write %s", genPath.c_str());
        return {};
    }
    FBZZ_LOG_INFO("FHT: generated -> %s", genPath.c_str());
    return genPath;
}

void ScriptCodeGen::GenerateReflectAll(const std::string& scriptsDir)
{
    if (scriptsDir.empty()) return;
    const std::filesystem::path dir(scriptsDir);
    if (!util::FileSystem::Exists(scriptsDir)) return;

    for (const auto& entry : std::filesystem::directory_iterator(dir)) {
        if (!entry.is_regular_file()) continue;
        const auto& path = entry.path();
        if (path.extension() != ".hpp") continue;
        // .generated.hpp はスキップ
        const std::string stem = path.stem().string();
        if (stem.size() >= 9 && stem.substr(stem.size() - 9) == "generated") continue;
        if (path.filename().string().find(".generated.") != std::string::npos) continue;
        GenerateReflect(path.string());
    }
}

} // namespace fbzz::editor
