// AUTO-GENERATED by ScriptCodeGen -- do not edit manually
// WHY: 実装を独立した TU に分離して DLL のビルドを並列化する。
//      SandboxScriptsDll.cpp はヘッダを宣言のみで取り込み、
//      このファイルが実装を担当することで Ninja が並列コンパイルできる。
// WHY: ScriptSceneProxy のテンプレート定義をこの TU から参照可能にする。
#include <Engine/Scene/Scene.hpp>
#include "Scripts/TpsCameraComponent.hpp"
