[app]
renderer = 'dx12'
targetFps = 360

[audio]
masterVolume = 1.0
voiceLimit = 48

    [[audio.bus]]
    name = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'BGM'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'SE'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'UI'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'Voice'
    parent = 'Master'
    volume = 1.0

[cursor]
hardware = true

    [cursor.shapes.Default]
    hotspot = [ 2.0, 2.0 ]
    image = 'Assets/Sprites/HUD/pointer_c_shaded.png'

[layers]
names = [
    'Default',
    'TransparentFX',
    'Ignore Raycast',
    '',
    'Water',
    'UI',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
]

[physics]
gravity = [ 0.0, -9.81, 0.0 ]
hz = 144
substeps = 1

[project]
default_scene = 'Assets/Scenes/Title.scene'
name = 'GreenWare'

[render]
clusteredDebugHeatmap = false
clusteredEnabled = true
clusteredForceAllLights = false
clusteredMaxDistance = 200.0
mode = 'PathTracing'
outlineColor = [ 1.0, 0.82, 0.22, 1.0 ]
outlineWidth = 0.045
particleBudget = 20000
particleBudgetEnabled = true
passViewerEnabled = false
pathProfile = 'Reference'
pcssEnabled = true
pcssLightRadius = 3.0
pipeline = 'Deferred+'
pipelineAsset = 'Assets/EditorConfig/RenderPipeline.fzdata'
rayDiffuseGi = true
rayReflection = true
rayShadow = true
shadow = true
shadowAutoFitDistance = 60.0
shadowCascadeBlend = 0.1
shadowCascadeCount = 4
shadowCascadeSplitLambda = 0.75
shadowPcfRadius = 3
shadowResolution = 4096
showColliders = false
showDecalBounds = false
showSelectionOutline = true
showUIRects = false
viewMode = 0

    [render.hybrid]
    asUpdateBudgetMs = 1.0
    frameBudgetMs = 8.333333
    glassBoundaryLimit = 16
    glassStochastic = true
    historyLimit = 32
    maxHistoryMiB = 512
    maxProbeCapturesPerFrame = 1
    maxTraceDistance = 0.0
    probeUpdateBudgetMs = 1.0
    reconstructionBudgetMs = 1.0
    reflectionResolutionDivisor = 2
    reflectionSamples = 1
    spatialRadius = 1
    traceBudgetMs = 3.0

[runtime]
start_scene = 'Assets/Scenes/Title.scene'

[screen]
height = 1080
width = 1920

[tags]
list = [ 'Untagged', 'Respawn', 'Finish', 'EditorOnly', 'MainCamera', 'Player', 'GameController' ]

[ui]
default_font = 'Assets/Fonts/Default/Roboto/Roboto-VariableFont_wdth,wght'

[window]
fullscreen = false
height = 1080
title = 'FBZZ Game'
width = 1920