[app]
renderer = 'dx12'
targetFps = 0

[audio]
masterVolume = 1.0

    [[audio.bus]]
    name = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'BGM'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'SE'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'UI'
    parent = 'Master'
    volume = 1.0

    [[audio.bus]]
    name = 'Voice'
    parent = 'Master'
    volume = 1.0

[layers]
names = [
    'Default',
    'TransparentFX',
    'Ignore Raycast',
    '',
    'Water',
    'UI',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
]

[physics]
gravity = [ 0.0, -9.81, 0.0 ]
hz = 144
substeps = 1

[project]
default_scene = 'Assets/Scenes/Title.scene'
name = 'GreenWare'

[render]
clusteredDebugHeatmap = false
clusteredEnabled = true
clusteredForceAllLights = false
clusteredMaxDistance = 200.0
outlineColor = [ 1.0, 0.82, 0.22, 1.0 ]
outlineWidth = 0.045
particleBudget = 20000
particleBudgetEnabled = true
passViewerEnabled = false
pcssEnabled = true
pcssLightRadius = 3.0
pipeline = 'Forward+'
shadow = true
shadowAutoFitDistance = 60.0
shadowCascadeBlend = 0.1
shadowCascadeCount = 4
shadowCascadeSplitLambda = 0.75
shadowPcfRadius = 2
shadowResolution = 4096
showColliders = false
showDecalBounds = false
showSelectionOutline = true
showUIRects = false
viewMode = 0

[runtime]
start_scene = 'Assets/Scenes/Title.scene'

[screen]
height = 1080
width = 1920

[tags]
list = [ 'Untagged', 'Respawn', 'Finish', 'EditorOnly', 'MainCamera', 'Player', 'GameController' ]

[ui]
default_font = 'Assets/Fonts/Default/Roboto/Roboto-VariableFont_wdth,wght'

[window]
fullscreen = false
height = 1080
title = 'FBZZ Game'
width = 1920