# @file    StageAgilitySDK.cmake
# @brief   ホスト EXE 基準の固定ランタイムと告知の同期。
# @author  Hasegawa Jin
# @date    2026-10-03
if(DEFINED FBZZ_DX12_ENABLED AND NOT FBZZ_DX12_ENABLED)
    file(WRITE "${FBZZ_OUTPUT}/fbzz-runtime.toml" "[sdk]\nschema = 2\n[runtime]\ndx12_enabled = false\n")
    return()
endif()
include("${FBZZ_AGILITY_LICENSES}/VERSION")
include("${FBZZ_DXC_LICENSES}/VERSION")
file(MAKE_DIRECTORY "${FBZZ_OUTPUT}/D3D12")
file(COPY_FILE "${FBZZ_CORE_SOURCE}/D3D12Core.dll" "${FBZZ_OUTPUT}/D3D12/D3D12Core.dll" ONLY_IF_DIFFERENT)
if(FBZZ_CONFIG STREQUAL "Debug" OR FBZZ_CONFIG STREQUAL "Development")
    file(COPY_FILE "${FBZZ_CORE_SOURCE}/d3d12SDKLayers.dll" "${FBZZ_OUTPUT}/D3D12/d3d12SDKLayers.dll" ONLY_IF_DIFFERENT)
else()
    file(REMOVE "${FBZZ_OUTPUT}/D3D12/d3d12SDKLayers.dll")
endif()
foreach(name dxcompiler.dll dxil.dll)
    file(COPY_FILE "${FBZZ_DXC_INPUT_DIRECTORY}/${name}" "${FBZZ_OUTPUT}/${name}" ONLY_IF_DIFFERENT)
endforeach()
file(SHA256 "${FBZZ_OUTPUT}/D3D12/D3D12Core.dll" coreHash)
file(SHA256 "${FBZZ_OUTPUT}/dxcompiler.dll" compilerHash)
file(SHA256 "${FBZZ_OUTPUT}/dxil.dll" validatorHash)
set(layersHash "")
if(EXISTS "${FBZZ_OUTPUT}/D3D12/d3d12SDKLayers.dll")
    file(SHA256 "${FBZZ_OUTPUT}/D3D12/d3d12SDKLayers.dll" layersHash)
endif()
if(NOT coreHash STREQUAL FBZZ_AGILITY_CORE_SHA256
    OR NOT compilerHash STREQUAL FBZZ_DXC_COMPILER_SHA256
    OR NOT validatorHash STREQUAL FBZZ_DXC_VALIDATOR_SHA256
    OR (NOT layersHash STREQUAL "" AND NOT layersHash STREQUAL FBZZ_AGILITY_LAYERS_SHA256))
    message(FATAL_ERROR "Staged Agility / DXC runtime SHA256 disagrees with the fixed package VERSION")
endif()
string(REPLACE "\\" "\\\\" manifestPath "${FBZZ_AGILITY_SDK_PATH}")
file(WRITE "${FBZZ_OUTPUT}/fbzz-runtime.toml"
    "[sdk]\nschema = 2\n[runtime]\ndx12_enabled = true\nagility_package = \"${FBZZ_AGILITY_PACKAGE_VERSION}\"\nagility_sdk_version = ${FBZZ_AGILITY_SDK_VERSION}\nagility_path = \"${manifestPath}\"\ncore_file_version = \"${FBZZ_AGILITY_CORE_FILE_VERSION}\"\ncore_sha256 = \"${coreHash}\"\nlayers_sha256 = \"${layersHash}\"\ndxc_compiler_sha256 = \"${compilerHash}\"\ndxc_validator_sha256 = \"${validatorHash}\"\n")
foreach(package AgilitySDK DXC WinPixEventRuntime)
    if(package STREQUAL "AgilitySDK")
        set(source "${FBZZ_AGILITY_LICENSES}")
        set(notices LICENSE LICENSE.txt LICENSE-CODE.txt VERSION "distributable files.txt")
    elseif(package STREQUAL "DXC")
        set(source "${FBZZ_DXC_LICENSES}")
        set(notices LICENSE LICENCE-MIT.txt LICENSE-LLVM.txt LICENSE-MS.txt VERSION)
    else()
        set(source "${FBZZ_PIX_LICENSES}")
        set(notices LICENSE ThirdPartyNotices.txt VERSION)
    endif()
    file(MAKE_DIRECTORY "${FBZZ_OUTPUT}/EngineLicenses/${package}")
    foreach(name IN LISTS notices)
        file(COPY_FILE "${source}/${name}" "${FBZZ_OUTPUT}/EngineLicenses/${package}/${name}" ONLY_IF_DIFFERENT)
    endforeach()
endforeach()
file(APPEND "${FBZZ_OUTPUT}/fbzz-runtime.toml" "\n[notices]\n")
file(GLOB_RECURSE noticeFiles LIST_DIRECTORIES FALSE "${FBZZ_OUTPUT}/EngineLicenses/*")
foreach(notice IN LISTS noticeFiles)
    file(RELATIVE_PATH relative "${FBZZ_OUTPUT}/EngineLicenses" "${notice}")
    file(SHA256 "${notice}" hash)
    file(APPEND "${FBZZ_OUTPUT}/fbzz-runtime.toml" "\"${relative}\" = \"${hash}\"\n")
endforeach()
